- name: install nodejs
  hosts: backend.vijayjohn.online
  become: yes
  tasks:
  - name: disable nodjs
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable nodjs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: add user
    ansible.builtin.user:
      name: expense
      
