- name: configure frontend
  hosts: vijayjohn.online
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove a directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create a directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory